version: "3.7"

services:
  db:
    image: postgres
    container_name: elastri-api-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5234:5234"
    volumes:
      - /var/lib/postgresql/data

  node:
    build: .
    container_name: elastri-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/server
    depends_on:
      - db
